name: siren 
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.0.1
  sms_advanced: ^1.0.2
  flutter_sms: ^2.3.3
  url_launcher: ^6.1.10
  #sms: ^0.2.4
  http: ^0.13.5
  intl: ^0.18.1
  fluttertoast: ^8.2.5
  connectivity_plus: ^2.3.9
  shared_preferences: ^2.1.1
  firebase_core: ^2.8.0
  #firebase_database: ^10.0.16
  firebase_auth: ^4.2.2
  firebase_database: ^10.0.16
  animated_toggle_switch: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app.webp"
